defaults:
  - user: default
  - machine: local
  # - data: bop
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:
  output_subdir: null
  run:
   dir: ./SAM-6D/Instance_Segmentation_Model/

level: 2
disable_output: true
num_workers: 4
gpus: "0,1,2,3"