_target_: model.fast_sam.FastSAM
checkpoint_path: ./SAM-6D/Instance_Segmentation_Model/checkpoints/pipe/elbow/best.pt
segmentor_width_size: ${model.segmentor_width_size}
config:
  iou_threshold: 0.5
  conf_threshold: 0.05
  max_det: 200